---
# The path to the public key to use in this automation.
ansible_public_key_file: "{{ lookup('env', 'PUBLIC_KEY')|default('~/.ssh/id_rsa.pub', true) }}"
# The path to the private key to access servers using the keypair.
ansible_private_key_file: "{{ lookup('env', 'PRIVATE_KEY')|default('~/.ssh/id_rsa', true) }}"
# The path to the local directory to store log files or build artifacts.
artifacts_directory: "{{ lookup('env', 'ARTIFACTS_DIR')|default('artifacts/openshift-' ~ ocp_major_minor, true) }}"
# The name of the cluster to use on this install.
clusterid: "{{ lookup('env', 'clusterid')|default('scale-ci', true) }}"
# The public dns domain for this cluster.
dns_domain: "{{ lookup('env', 'dns_domain')|default('example.com', true) }}"
# The remote directory to store any scale-ci files.
install_directory: "{{ ansible_user_dir }}/{{ clusterid }}"
# The remote directory to store the scale-ci log files.
log_directory: "{{ ansible_user_dir }}/logs"
# The version of OpenShift Container Platform to install and test.
ocp_major_minor: "{{ lookup('env', 'ocp_major_minor')|default('3.11', true) }}"
# Look up the environment variable with a space separated string of time servers.
time_servers: "{{ lookup('env', 'time_servers')|default('0.pool.ntp.org 1.pool.ntp.org 2.pool.ntp.org 3.pool.ntp.org', true)|trim }}"
# Break up the space separated string into a list of time servers.
time_servers_list: "{{ time_servers.split(' ') }}"
# The virtual image name to use in OpenStack when creating virtual servers.
virtual_image_name: "{{ lookup('env', 'default_image_name')|default('ocp-' ~ ocp_major_minor ~ '-rhel', true) }}"
