---
#
# Clean up cluster
#

- name: Check if a cluster is running
  stat:
    path: "{{ ansible_user_dir }}/scale-ci-deploy/scale-ci-{{ platform }}/metadata.json"
  register: cluster_status

- block:
    - name: Cleanup cluster
      shell: |
        cd {{ ansible_user_dir }}/scale-ci-deploy
        export GOOGLE_CREDENTIALS={{ gcp_auth_key_file|default() }}
        bin/openshift-install destroy cluster --log-level=debug --dir={{ ansible_user_dir }}/scale-ci-deploy/scale-ci-{{ platform }}/
    - name: Clean scale-ci-deploy openshift-install directories
      become: true
      file:
        path: "{{item}}"
        state: absent
      with_items:
        - "{{ ansible_user_dir }}/scale-ci-deploy/bin"
        - "{{ ansible_user_dir }}/scale-ci-deploy/scale-ci-{{ platform }}"
  when: cluster_status.stat.exists == True
