---
- name: Find the target-server and add it to the in-memory inventory
  hosts: openstack-server
  vars_files:
    - vars/openstack.yml
  roles:
    - openstack_get_server

- name: Create additional OpenStack VMs and add them to OpenShift
  hosts: target-server
  vars_files:
    - vars/openstack.yml
    - vars/openshift.yml
  roles:
    - openshift_on_openstack_scale
