---
# The algorithm to use when creating the DNS update key.
dns_key_algorithm: "{{ lookup('env', 'dns_key_algorithm')|default('hmac-md5', true) }}"
# The DNS update key file name.
dns_key_file: "{{ lookup('env', 'dns_update_file')|default('dns_update.key', true) }}"
# The key name when creating the DNS update key.
dns_key_name: "{{ lookup('env', 'dns_key_name')|default('update-key', true) }}"
# The file name to store the nsupdate information.
nsupdate_file: "{{ lookup('env', 'nsupdate_file')|default(ansible_user_dir ~ '/nsupdate_keys.yml', true) }}"
