---
- name: Getting the floating ip address of the first master
  set_fact:
    master_address: "{{ hostvars[groups.masters[0]].public_ip }}"
  when: groups["masters"] is defined and groups.masters | length > 0

- name: Refuse to continue if master address is not defined
  fail:
    msg: "Master address is not defined."
  when: master_address is not defined or master_address == ""

- name: Adding the MASTER_HOSTNAME to the properties file
  lineinfile:
    line: "MASTER_HOSTNAME={{ master_address }}"
    path: "{{ properties_file }}"
  delegate_to: localhost

- name: Adding the MASTER_USER to the properties file
  lineinfile:
    line: "MASTER_USER=openshift"
    path: "{{ properties_file }}"
  delegate_to: localhost

- name: Adding ENABLE_PBENCH to the properties file
  lineinfile:
    line: "ENABLE_PBENCH=True"
    path: "{{ properties_file }}"
  delegate_to: localhost

- name: Reading the {{ properties_file }}
  set_fact:
    properties_contents: "{{ lookup('file', properties_file) }}"
  delegate_to: localhost

- name: Printing the contents {{ properties_file }}
  debug:
    msg: "{{ properties_contents }}"
