---
# Read the DNS update key file.
- name: Reading the remote {{ dns_key_file }} file
  command: "grep secret {{ dns_key_file }}"
  register: update_secret
  changed_when: false

# Create a regular expression to get the secret key.
- name: Setting the regular expression to find the secret
  set_fact:
    # Example:        secret "8kjyy/xFvzapFwmcWwLzvA==";
    secret_regex: 'secret "(.*)";'

# Get the DNS server addresses from OpenStack.
- name: Getting the IP address for the DNS VM ns-master
  shell: "{{ openstack }} server show ns-master.{{ clusterid}}.{{ dns_domain }} --format value -c addresses"
  # "ns-master-scale-ci.example.com-net=192.168.99.17, 172.21.0.129"
  register: dns_addresses
  changed_when: false

# Parse the IP address from the addresses output.
- name: Parsing the floating ip from the DNS VM addresses
  set_fact:
    cluster_dns_ip: "{{ dns_addresses['stdout'].split(', ')[1] }}"
  failed_when: cluster_dns_ip == ""

# Set the DNS secret value.
- name: Creating a variable with the DNS secret value
  set_fact:
    dns_key_secret: "{{ update_secret['stdout']|regex_findall(secret_regex)|first }}"

- name: "Remove DNS A records"
  nsupdate:
    key_name: "{{ dns_key_name }}"
    key_secret: "{{ dns_key_secret }}"
    key_algorithm: "{{ dns_key_algorithm }}"
    server: "{{ cluster_dns_ip }}"
    zone: "{{ clusterid }}.{{ dns_domain }}"
    record: "{{ item.name }}"
    type: "A"
    state: absent
  with_items:
    - "{{ hosts_new | default([]) }}"
  register: nsupdate_remove_result
  until: nsupdate_remove_result is succeeded
  retries: 10
  delay: 1

- name: "Add DNS A records"
  nsupdate:
    key_name: "{{ dns_key_name }}"
    key_secret: "{{ dns_key_secret }}"
    key_algorithm: "{{ dns_key_algorithm }}"
    server: "{{ cluster_dns_ip }}"
    zone: "{{ clusterid }}.{{ dns_domain }}"
    record: "{{ item.name }}"
    type: "A"
    value: "{{ item.private_ip }}"
    state: present
  with_items:
    - "{{ hosts_new | default([]) }}"
  register: nsupdate_add_result
  until: nsupdate_add_result is succeeded
  retries: 10
