---
# Rough equivalents of the Amazon ec2 flavors.
ec2_flavors:
  # https://aws.amazon.com/ec2/previous-generation/
  - { name: m1.small, vcpu: 1, memory: 1740, disk: 71 }
  - { name: m1.medium, vcpu: 1, memory: 3840, disk: 96 }
  - { name: m1.large, vcpu: 2, memory: 7680, disk: 128 }
  # https://aws.amazon.com/ec2/instance-types/#m4
  - { name: m4.large, vcpu: 2, memory: 8192, disk: 100 }
  - { name: m4.xlarge, vcpu: 4, memory: 16384, disk: 200 }
  - { name: m4.2xlarge, vcpu: 8, memory: 32768, disk: 300 }
  - { name: m4.4xlarge, vcpu: 16, memory: 65536, disk: 400 }
  - { name: m4.10xlarge, vcpu: 40, memory: 163840, disk: 500 }
  # https://aws.amazon.com/ec2/instance-types/#r4
  - { name: r4.large, vcpu: 2, memory: 15616, disk: 71 }
  - { name: r4.xlarge, vcpu: 4, memory: 31232, disk: 71 }
  - { name: r4.2xlarge, vcpu: 8, memory: 62464, disk: 96 }
  - { name: r4.4xlarge, vcpu: 16, memory: 124928, disk: 128 }
  - { name: r4.8xlarge, vcpu: 32, memory: 249856, disk: 256 }
  - { name: r4.16xlarge, vcpu: 64, memory: 499712, disk: 512 }
# The OpenShift flavors for the different roles.
openshift_flavors:
  - { name: container_storage, vcpu: 16, memory: 65536, disk: 128, property: '--property "pci_passthrough:alias"="nvme:1"' }
  - { name: load_balancer, vcpu: 4, memory: 16384, disk: 128 }
  - { name: infra_elastic, vcpu: 40, memory: 163840, disk: 128, property: '--property "pci_passthrough:alias"="nvme:1"' }
  - { name: master_etcd, vcpu: 16, memory: 124928, disk: 256, property: '--property "pci_passthrough:alias"="nvme:1"' }
  - { name: node_minimum, vcpu: 1, memory: 2048, disk: 71 }
  - { name: node_small, vcpu: 2, memory: 8192, disk: 96 }
  - { name: node_medium, vcpu: 4, memory: 16384, disk: 128 }
  - { name: node_large, vcpu: 8, memory: 31744, disk: 160 }
# The path to the OpenStack RC file on the openstack-server, may be named differently than other servers.
openstack_rc: "{{ lookup('env', 'openstack_rc_path')|default(ansible_user_dir ~ '/overcloudrc', true) }}"
# The path to the private key, put it the install directory for easy cleanup.
remote_private_key_path: "{{ lookup('env', 'remote_private_key_path')|default(install_directory ~ '/key.private', true) }}"
# The path to the public key, put it in the install directory for easy cleanup.
remote_public_key_path: "{{ lookup('env', 'remote_public_key_path')|default(install_directory ~ '/key.public', true) }}"
# The quota structure to set for this OpenStack project.
quotas:
  backup-gigabytes: -1
  backups: -1
  cores: -1           # Number of instance cores (VCPUs) allowed per project.
  fixed-ips: -1
  floating-ips: -1    # Number of floating IP addresses allowed per project.
  gigabytes: -1       # Volume gigabytes allowed for each project.
  injected-file-size: -1
  injected-files: -1
  injected-path-size: -1
  instances: -1       # Number of instances (VMs) allowed per project.
  key-pairs: -1       # Number of key pairs allowed per project.
  networks: -1
  ports: -1
  properties: -1
  ram: -1             # Megabytes of instance ram allowed per project.
  rbac-policies: -1
  routers: -1
  secgroup-rules: -1
  secgroups: -1       # Security groups allowed for each project.
  server-group-members: -1
  server-groups: -1
  snapshots: -1       # Volume snapshots allowed for each project.
  subnets: -1
  volumes: -1         # Volumes allowed for each project.

# Rough equivalents of the Google cloud instance sizes.
standard_flavors:
  # https://cloud.google.com/compute/docs/machine-types
  - { name: n1-standard-1, vcpu: 1, memory: 3750, disk: 71 }
  - { name: n1-standard-2, vcpu: 2, memory: 7500, disk: 80 }
  - { name: n1-standard-4, vcpu: 4, memory: 15000, disk: 80 }
  - { name: n1-standard-8, vcpu: 8, memory: 30000, disk: 100 }
  - { name: n1-standard-16, vcpu: 16, memory: 60000, disk: 100 }
  - { name: n1-standard-32, vcpu: 32, memory: 120000, disk: 200 }
  - { name: n1-standard-64, vcpu: 64, memory: 240000, disk: 200 }
