---
# The path to the all.yml file on the target-server.
all_yml_path: "{{ ansible_user_dir }}/inventory/group_vars/all.yml"
# The path to the all.yml.cfg (all.yml override) file on the target-server.
all_yml_cfg_path: "{{ ansible_user_dir }}/inventory/group_vars/all.yml.cfg"
# The path to the OpenStack RC file on the server vm, may be named differently than other servers.
openstack_rc: "{{ ansible_user_dir }}/keystonerc"
# The path to the OSEv3.yml file on the target-server.
osev3_yml_path: "{{ ansible_user_dir }}/inventory/group_vars/OSEv3.yml"
# The path to the OSEv3.yml.cfg (OSEv3.yml override) file on the target-server.
osev3_yml_cfg_path: "{{ ansible_user_dir }}/inventory/group_vars/OSEv3.yml.cfg"
