---
#
# Installs a 3.X OpenShift Cluster on OpenStack
#

- name: Enable nested virt on the hypervisors
  hosts: undercloud
  user: stack
  vars_files:
    - vars/install.yml
  roles:
    - role: openstack_nested_virtualization
      when: openstack_nested_virtualization | default(True) | bool

- name: Find and prepare OCP image files
  hosts: image-server
  remote_user: root
  vars_files:
    - vars/install.yml
  pre_tasks:
    - name: Ensure the local artifacts directory exists
      file:
        path: "{{ artifacts_dir }}"
        state: directory
      delegate_to: localhost
  roles:
    - role: image_preparation
      when: openstack_upload_images | default(True) | bool

- name: Create OpenStack resources, upload OCP images and create Bastion machine
  hosts: undercloud
  remote_user: stack
  vars_files:
    - vars/install.yml
  roles:
    - name: update-motd
      vars:
        update_motd: Creating OCP Cluster OSP Resources
    - openstack_create_overcloud_resources
    - role: openstack_upload_images
      when: openstack_upload_images | default(True) | bool
    - openstack_create_bastion

- name: Install OpenShift on OpenStack
  hosts: bastion
  gather_facts: false
  vars_files:
    - vars/install.yml
  roles:
    - openshift_configure_bastion
    - pbench_storage
    - name: update-motd
      vars:
        update_motd: Installing OCP Cluster DNS
    - openshift_dns
    - name: update-motd
      vars:
        update_motd: Installing OCP Cluster
    - openshift_on_openstack_install
    - role: openshift_metering
      when: ocp_metering_install|bool
    - name: update-motd
      vars:
        update_motd: Finished Installing OCP Cluster

- name: Add core cluster to inventory
  hosts: undercloud
  remote_user: stack
  vars:
    openshift_core_cluster: []
  vars_files:
    - vars/install.yml
  roles:
    - name: update-motd
      vars:
        update_motd: Finishing OCP Cluster Configuration
    - openstack_add_fips
    - openshift_get_core_cluster
    - etc_hosts

- name: Use the remaining disk space on the core cluster for Pbench
  hosts: masters infras lb cns app_nodes
  vars_files:
    - vars/install.yml
  roles:
    - pbench_storage

- name: Run post OpenShift installation tasks
  hosts: bastion
  vars_files:
    - vars/install.yml
  roles:
    - openshift_copy_kube_config
    - etc_hosts
    - openshift_dns_wildcard
    - pbench_web_server
  post_tasks:
    - name: label the application nodes in the core cluster
      shell: oc label node {{ item }}.{{ clusterid }}.{{ dns_domain }} core_app_node=true
      with_items:
        - "{{ groups['app_nodes'] }}"

- name: Copy the certs to the location where golang looks for
  hosts: masters
  vars_files:
    - vars/install.yml
  become: yes
  tasks:
    - name: copy the certs on masters
      copy:
        src: /etc/origin/master/ca.crt
        dest: /etc/ssl/certs/
        remote_src: true
