---
# The path to the OpenStack RC file on the server vm, may be named differently than other servers.
openstack_rc: "{{ lookup('env', 'openstack_rc_path')|default(ansible_user_dir ~ '/keystonerc', true) }}"
# A dictionary of packages to install for different families of operating systems.
packages:
  common:
    - curl
    - bind
    - gcc
    - git
    - libselinux-python
    - redhat-rpm-config
    - python-crypto
    - sshpass
  Fedora:
    - python2-devel
    - python2-virtualenv
  CentOS:
    - epel-release
    - python-devel
    - python-virtualenv
  RedHat:
    - python-devel
    - python-virtualenv
  python:
    - ansible==2.4.2
    - cliff==2.4.0
    - dnspython==1.12.0
    - Jinja2==2.7.2
    - jmespath==0.9.0
    - osc-lib==1.3.0
    - python-openstackclient==3.8.1
    - python-heatclient==1.8.0
    - shade==1.26.0
pip: pip
# When the virtualenv_directory is defined, a Python virtual environment is created.
# virtualenv_directory: virtualenv
