---
- name: Installing the chrony software
  package:
    name: chrony
    state: installed
  become: true

- name: Rendering the chrony configuration
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
  become: true

- name: Restarting the chrony service
  service:
    name: chronyd
    state: restarted
    enabled: yes
  become: true
