---
#
# Populates nodes with kubeconfig and ssh configuration for easier debugging
#

- name: Ensure that .kube dir exists
  file:
    path: "{{item.path}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    state: directory
  with_items:
    - path: /home/core/.kube
      owner: core
      group: core
    - path: /root/.kube
      owner: root
      group: root

- name: Copy the kubeconfig to a node
  copy:
    src: "{{playbook_dir}}/kubeconfig"
    dest: "{{item.dest}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
  with_items:
    - dest: /home/core/.kube/config
      owner: core
      group: core
    - dest: /root/.kube/config
      owner: root
      group: root
  when:
    - kubeconfig_auth_dir_path == ""

# Handle case where kubeconfig is in another specified dir
- name: Copy the kubeconfig to node from specific directory
  copy:
    src: "{{ kubeconfig_auth_dir_path }}/auth/kubeconfig"
    dest: "{{ item.dest }}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
  with_items:
    - dest: /home/core/.kube/config
      owner: core
      group: core
    - dest: /root/.kube/config
      owner: root
      group: root
  when:
    - kubeconfig_auth_dir_path != ""

- name: Ensure that ssh dir exists
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{item.owner}}"
    group: "{{item.group}}"
  with_items:
    - path: /home/core/.ssh
      owner: core
      group: core
    - path: /root/.ssh
      owner: root
      group: root

- name: Copy authorized keys
  copy:
    src: /home/core/.ssh/authorized_keys
    dest: /root/.ssh/authorized_keys
    remote_src: yes
    owner: root
    group: root

- name: Copy private key to a node
  copy:
    src: "{{ansible_ssh_private_key_file}}"
    dest: "{{ item.dest }}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    mode: 0600
  with_items:
    - dest: /home/core/.ssh/id_rsa
      owner: core
      group: core
    - dest: /root/.ssh/id_rsa
      owner: root
      group: root

- name: Permit root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "PermitRootLogin no"
    line: "PermitRootLogin yes"

- name: Restart sshd
  systemd:
    name: sshd
    state: restarted
